name: "💡 New Feature"
description: Propose a new feature idea for StrokkCommands.
labels:
  - "awaiting response"
  - "feature"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a feature request! Please be as detailed as possible to help me review and consider your request effectively.
        Before submitting, please ensure the following:

        1. You are using the latest version of StrokkCommands (you can see the latest up-to-date dependency by visiting https://commands.strokkur.net/docs/dependency)
           and the feature you’re requesting isn’t already included in the version you’re using.
        2. You’ve searched for and confirmed there isn’t already [an open request](https://github.com/Strokkur424/StrokkCommands/issues?q=is%3Aissue%20is%3Aopen%20type%3AFeature) for this feature.
            - If a similar request exists, feel free to add any additional details you think are helpful.

  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      description: Please provide some context for this request. Why do you want it added?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the solution you'd like.
      description: A clear and concise description of what you want.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe alternatives you've considered.
      description: List any alternatives you might have tried to get the feature you want.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Other
      description: Add any other context or screenshots about the feature request below.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Before submitting this feature request, please search our issue tracker to ensure your feature has not
        already been requested.