name: 'Docs: Format Check'

env:
  BASE_DIR: docs

on: [ pull_request ]

jobs:
  format:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ${{ env.BASE_DIR }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: 'package.json'

      - name: Install dependencies
        run: bun install --frozen-lockfile
        
      - name: Check format
        run: bun format:check