name: 'Docs: Format Check'

env:
  BASE_DIR: docs

on: [ pull_request ]

jobs:
  format:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
          package_json_file: '${{ env.BASE_DIR }}/package.json'

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: '${{ env.BASE_DIR }}/pnpm-lock.yaml'

      - name: Install dependencies
        working-directory: ${{ env.BASE_DIR }}
        run: pnpm install --frozen-lockfile
        
      - name: Check format
        working-directory: ${{ env.BASE_DIR }}
        run: pnpm format:check