name: 'StrokkCommands: Publish Snapshot'

on:
  pull_request:
    branches: [ "main", "dev*" ]

jobs:
  publish:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'publish snapshot') }}
    name: Publish Snapshot to EldoNexus
    environment: publish-snapshot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: oracle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish
        run: ./gradlew publish
        env:
          SKIP_TESTS: "true"
          NEXUS_USERNAME: "${{ secrets.NEXUS_USERNAME }}"
          NEXUS_PASSWORD: "${{ secrets.NEXUS_PASSWORD }}"
