name: Publish

on:
  push:
    branches: [ "main", "dev*" ]

jobs:
  publish:
    environment: build
    runs-on: ubuntu-latest
    name: Publish to EldoNexus
    
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Add execution permissions to Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Publish
        run: ./gradlew publish
        env:
          NEXUS_USERNAME: "${{ secrets.NEXUS_USERNAME }}"
          NEXUS_PASSWORD: "${{ secrets.NEXUS_PASSWORD }}"
